/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Jannete
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ForAutor = new javax.swing.JMenuItem();
        ObtenerAutores = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        ForEjemplar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        ForLector = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        ForLibro = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        ForMulta = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        ForPrestamo = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu3.setText("Archivo");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Autor");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        ForAutor.setText("Formulario Autor");
        ForAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForAutorActionPerformed(evt);
            }
        });
        jMenu4.add(ForAutor);

        ObtenerAutores.setText("Obtener Autores");
        ObtenerAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtenerAutoresActionPerformed(evt);
            }
        });
        jMenu4.add(ObtenerAutores);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ejemplar");

        ForEjemplar.setText("Formulario Ejemplar");
        ForEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForEjemplarActionPerformed(evt);
            }
        });
        jMenu5.add(ForEjemplar);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Lector");

        ForLector.setText("Formulario Lector");
        ForLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForLectorActionPerformed(evt);
            }
        });
        jMenu6.add(ForLector);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Libro");

        ForLibro.setText("Formulario Libro");
        ForLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForLibroActionPerformed(evt);
            }
        });
        jMenu7.add(ForLibro);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Multa");

        ForMulta.setText("Formulario Multa");
        ForMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForMultaActionPerformed(evt);
            }
        });
        jMenu8.add(ForMulta);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Prestamo");

        ForPrestamo.setText("Formulario Prestamo");
        ForPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForPrestamoActionPerformed(evt);
            }
        });
        jMenu9.add(ForPrestamo);

        jMenuBar1.add(jMenu9);

        jMenu11.setText("Consultas");

        jMenuItem2.setText("jMenuItem2");
        jMenu11.add(jMenuItem2);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForAutorActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaAutor va = new VistaAutor();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_ForAutorActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void ForEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForEjemplarActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaEjemplar ve = new VistaEjemplar();
        ve.setVisible(true);
        escritorio.add(ve);
        escritorio.moveToFront(ve);
    }//GEN-LAST:event_ForEjemplarActionPerformed

    private void ForLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForLectorActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaLector vl = new VistaLector();
        vl.setVisible(true);
        escritorio.add(vl);
        escritorio.moveToFront(vl);
    }//GEN-LAST:event_ForLectorActionPerformed

    private void ForLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForLibroActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaLibro vli = new VistaLibro();
        vli.setVisible(true);
        escritorio.add(vli);
        escritorio.moveToFront(vli);
    }//GEN-LAST:event_ForLibroActionPerformed

    private void ForMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForMultaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaMulta vm = new VistaMulta();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_ForMultaActionPerformed

    private void ForPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForPrestamoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaPrestamo vp = new VistaPrestamo();
        vp.setVisible(true);
        escritorio.add(vp);
        escritorio.moveToFront(vp);
    }//GEN-LAST:event_ForPrestamoActionPerformed

    private void ObtenerAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtenerAutoresActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaObtenerAutores vo = VistaObtenerAutores();
        vo.setVisible(true);
        escritorio.add(vo);
        escritorio.moveToFront(vo);
    }//GEN-LAST:event_ObtenerAutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ForAutor;
    private javax.swing.JMenuItem ForEjemplar;
    private javax.swing.JMenuItem ForLector;
    private javax.swing.JMenuItem ForLibro;
    private javax.swing.JMenuItem ForMulta;
    private javax.swing.JMenuItem ForPrestamo;
    private javax.swing.JMenu ObtenerAutores;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    private VistaObtenerAutores VistaObtenerAutores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
